import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useMemo, useState } from "react";
import styles from "../styles/Home.module.css";
import { query, orderBy, getDocs, collection } from "firebase/firestore";
import { db } from "../firebase";
import { Game } from "../functions/src";

const sorts = ["percentRecommended", "averageScore", "medianScore"];

const Home: NextPage = () => {
  const [games, setGames] = useState<Game[]>([]);
  const [hidden, setHidden] = useState<string[]>([]);
  const [sort, setSort] = useState(sorts[0]);

  console.log("games", games);
  useEffect(() => {
    const ref = collection(db, "games");

    const q = query(ref, orderBy(`opencritic.${sort}`, "desc"));
    getDocs(q).then((querySnapshot) => {
      const games: any[] = [];
      querySnapshot.forEach((doc) => {
        games.push(doc.data());
      });
      setGames(games);
    });
  }, [sort]);

  function hideGame(id: string) {
    setHidden((state) => [...state, id]);
  }

  function round(n: number) {
    return Math.max(0, Math.round(n));
  }

  const filteredGames = useMemo(() => {
    return games.filter((game) => !hidden.includes(game.id));
  }, [games, hidden]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sorts.map((sort) => (
        <button key={sort} onClick={() => setSort(sort)}>
          {sort}
        </button>
      ))}
      <table>
        <thead>
          <tr>
            <th>Image</th>
            <th>Game</th>
            <th>Recommended</th>
            <th>Average score</th>
            <th>Median score</th>
            <th>Category</th>
            <th>Hide</th>
          </tr>
        </thead>
        <tbody>
          {filteredGames.map((game) => (
            <tr key={game.id}>
              <td>
                <img src={game.images[0]} style={{ width: 100 }} />
              </td>
              <td>{game.name}</td>
              <td>{round(game.opencritic.percentRecommended)}%</td>
              <td>{round(game.opencritic.averageScore)}%</td>
              <td>{round(game.opencritic.medianScore)}%</td>
              <td>{game.category}</td>
              <td>
                <button onClick={() => hideGame(game.id)}>Hide game</button>
              </td>
            </tr>
          ))}
          <tr></tr>
        </tbody>
      </table>
    </div>
  );
};

export default Home;
