const foo = {
  LastModifiedDate: "2021-12-07T00:56:40.5776737Z",
  LocalizedProperties: [
    {
      DeveloperName: "Asobo Studio",
      PublisherName: "Focus Home Interactive",
      PublisherWebsiteUri: "http://aplaguetale.com/",
      SupportUri: "https://www.focus-home.com/support",
      EligibilityProperties: {
        Remediations: [
          {
            RemediationId: "9ZH7BH6P9RM7",
            Description:
              "Go Gold today to take advantage of exclusive Xbox discounts, special deals, and offers.",
          },
          {
            RemediationId: "9SQ1C79LQTJJ",
            Description:
              "With Xbox Game Pass, you can play more great games anytime.",
          },
        ],
        Affirmations: [
          {
            AffirmationId: "9VP428G6BQ82",
            AffirmationProductId: "CFQ7TTC0KGQ8",
            Description: "with your Xbox Game Pass membership",
          },
        ],
      },
      Franchises: [],
      Images: [
        {
          FileId: "2000000000037721284",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 1245474,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "",
          ImagePurpose: "Poster",
          UnscaledImageSHA256Hash:
            "FDjuEwRvcM7Mh5OmN44iKeczz6Z8ooOkFPPgIUqGRjo=",
          Uri: "//store-images.s-microsoft.com/image/apps.14356.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.aa73acc4-f944-4ab1-83c3-265506b1529d",
          Width: 720,
        },
        {
          FileId: "2000000000037721298",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 1759546,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "",
          ImagePurpose: "BoxArt",
          UnscaledImageSHA256Hash:
            "zPGkhQ5Jzg0lYrw0aQZQasWFrst7Tj9SRi5LTNvQNdI=",
          Uri: "//store-images.s-microsoft.com/image/apps.61900.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.7472e56d-b2da-462f-8312-d12050d56ec6",
          Width: 1080,
        },
        {
          FileId: "2000000000037721285",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2348556,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "",
          ImagePurpose: "SuperHeroArt",
          UnscaledImageSHA256Hash:
            "TMKnYlYT0ecJE5rr/2X0B5vVf1q1Wu6dpp/qYI2iiR4=",
          Uri: "//store-images.s-microsoft.com/image/apps.49740.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.4bb59d7f-53c0-43d1-9ef2-20f2de8e893a",
          Width: 1920,
        },
        {
          FileId: "2000000000037721281",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 648498,
          ForegroundColor: "",
          Height: 800,
          ImagePositionInfo: "",
          ImagePurpose: "BrandedKeyArt",
          UnscaledImageSHA256Hash:
            "KwZyT4Ch07W8R4u2Yx0rGCV0j2y7hobHzj3Zp48arys=",
          Uri: "//store-images.s-microsoft.com/image/apps.1579.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.e15038e2-47a6-4d46-aa9c-c03298b73901",
          Width: 584,
        },
        {
          FileId: "2000000000037721282",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2204697,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "",
          ImagePurpose: "TitledHeroArt",
          UnscaledImageSHA256Hash:
            "qtt6H7NM0hyH5Y8Py0hGfEm76xl+ftzH6JoBxntc8I0=",
          Uri: "//store-images.s-microsoft.com/image/apps.56234.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.44048e8a-120d-4c3c-9a6d-a2e7df123548",
          Width: 1920,
        },
        {
          FileId: "2000000000037721330",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 1943970,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "",
          ImagePurpose: "FeaturePromotionalSquareArt",
          UnscaledImageSHA256Hash:
            "ppSaIy/yiQCtveGcCX1PGHNXz1swYo3Z5qwLix3mjAw=",
          Uri: "//store-images.s-microsoft.com/image/apps.38054.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.1d7d1199-fbd0-449b-8fd0-b0d3c173b17d",
          Width: 1080,
        },
        {
          FileId: "2000000000050783858",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 3758118,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/0",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "UnfJ6dCeNrzcTjiQ9ve5E07FmHH2ZxqV4v+Blgvfs3A=",
          Uri: "//store-images.s-microsoft.com/image/apps.30546.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.7fcbb4ea-29f0-48cf-b14a-3ed4223916a0",
          Width: 1920,
        },
        {
          FileId: "2000000000050783933",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2064356,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/1",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "Iv1uJ22JKh/54+3mZ75ZUFIkRBYjdAlhsVuNG5AQktQ=",
          Uri: "//store-images.s-microsoft.com/image/apps.64802.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.dc458d66-a8e7-462b-9745-03a4085f63b9",
          Width: 1920,
        },
        {
          FileId: "2000000000050783971",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2303607,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/2",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "70jC4cILygFuDG8G9OLWsYVIG6cHca0Kx3ytPQGcmeE=",
          Uri: "//store-images.s-microsoft.com/image/apps.18671.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.b1197dca-669a-4d12-ae92-64c7071ca531",
          Width: 1920,
        },
        {
          FileId: "2000000000050784014",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 3034559,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/3",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "wIcav4BRtgTVi4qoEhUCdnuDIDbM46zjVhGIFc4A74M=",
          Uri: "//store-images.s-microsoft.com/image/apps.34752.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.551d5ef7-948a-4840-bb2e-1ec7e5b3c73f",
          Width: 1920,
        },
        {
          FileId: "2000000000050784003",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2493664,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/4",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "dSYsLL2++J1j7mIjrDFma/ynQep/JCrRXxVvnzTDv1g=",
          Uri: "//store-images.s-microsoft.com/image/apps.9845.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.b723ece7-2573-4b5a-ab38-f11d3b309b19",
          Width: 1920,
        },
        {
          FileId: "2000000000050784007",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2441146,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/5",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "5cNUSSqzGsSQ7wm4IH9NDhT8eMIOXCVy5000ZkRT9+E=",
          Uri: "//store-images.s-microsoft.com/image/apps.50149.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.759e72ee-e2dc-433b-8eee-920befa957cc",
          Width: 1920,
        },
        {
          FileId: "2000000000050784009",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 3927626,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/6",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "7oVKc530GIozJ1760FE7KJ7zlRLWnYN8YK0d709eNhw=",
          Uri: "//store-images.s-microsoft.com/image/apps.34286.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.15e8cac0-c2c2-4b92-a2eb-cb670b63bb51",
          Width: 1920,
        },
        {
          FileId: "2000000000050784071",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2458566,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/7",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "0i4mlsrYwrsRYTmu5WVInySmOkJI0VqtIR/yr9lRv/w=",
          Uri: "//store-images.s-microsoft.com/image/apps.11986.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.df9664f2-f8d6-4826-bd06-a6b300da366c",
          Width: 1920,
        },
        {
          FileId: "2000000000050784122",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2491051,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/8",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "eDxkASvg9wm1A2KJrw1w3UI8efK0YVFTWdj5/Yk50MU=",
          Uri: "//store-images.s-microsoft.com/image/apps.15480.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.e18bdccc-34b0-4e5d-b778-2480a0e1ee15",
          Width: 1920,
        },
        {
          FileId: "2000000000050784125",
          EISListingIdentifier: null,
          BackgroundColor: "",
          Caption: "",
          FileSizeInBytes: 2968490,
          ForegroundColor: "",
          Height: 1080,
          ImagePositionInfo: "Desktop/9",
          ImagePurpose: "Screenshot",
          UnscaledImageSHA256Hash:
            "aM4jZgoVCIEEuCmwZzIjaRCzx07W2/nEaUyI/kmz+WM=",
          Uri: "//store-images.s-microsoft.com/image/apps.52840.13558110806647450.785aaa6b-d3b1-420b-90db-60148ed7c454.542788ae-fff0-41de-9507-4d35dfde77d6",
          Width: 1920,
        },
      ],
      Videos: [
        {
          Uri: "http://universalstore.streaming.mediaservices.windows.net/ab3e2be8-bfb9-4dfc-8068-9324ef7dcb40/23b10afe-a333-4f40-a1cb-da052ff6.ism/manifest",
          VideoPurpose: "trailer",
          Height: 1080,
          Width: 1920,
          AudioEncoding: "",
          VideoEncoding: "avc1",
          VideoPositionInfo: "Video/0",
          Caption: "Accolade Trailer",
          FileSizeInBytes: 280122551,
          PreviewImage: {
            FileId: "2000000000037721797",
            EISListingIdentifier: null,
            BackgroundColor: null,
            Caption: "Accolade Trailer",
            FileSizeInBytes: 1293751,
            ForegroundColor: null,
            Height: 1080,
            ImagePositionInfo: null,
            ImagePurpose: "trailer",
            UnscaledImageSHA256Hash:
              "d0HTidKj+XFSZSEiwCiEW8Wk5CjTW9zNnWPxBdkoMjk=",
            Uri: "//store-images.s-microsoft.com/image/apps.16759.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.6c2a0a16-4174-45c2-b172-a271d4125e3a",
            Width: 1920,
          },
          SortOrder: 1,
        },
        {
          Uri: "http://universalstore.streaming.mediaservices.windows.net/74a805b4-aa52-49f9-b784-ba1cfc27e9b1/741ce7ba-2770-4c77-9180-6af8142b.ism/manifest",
          VideoPurpose: "trailer",
          Height: 1080,
          Width: 1920,
          AudioEncoding: "",
          VideoEncoding: "avc1",
          VideoPositionInfo: "Video/0",
          Caption: "The Little Boy Lost",
          FileSizeInBytes: 197939143,
          PreviewImage: {
            FileId: "2000000000037721801",
            EISListingIdentifier: null,
            BackgroundColor: null,
            Caption: "The Little Boy Lost",
            FileSizeInBytes: 1444241,
            ForegroundColor: null,
            Height: 1080,
            ImagePositionInfo: null,
            ImagePurpose: "trailer",
            UnscaledImageSHA256Hash:
              "eb6v1+kfIMU/OrNmWoVXaxHycnMGXKJENUkx/QdpjoU=",
            Uri: "//store-images.s-microsoft.com/image/apps.48761.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.9fdf1c54-f244-4b76-b01d-5539f607e755",
            Width: 1920,
          },
          SortOrder: 2,
        },
      ],
      ProductDescription:
        "Follow the grim tale of young Amicia and her little brother Hugo, in a heartrending journey through the darkest hours of history. Hunted by Inquisition soldiers and surrounded by unstoppable swarms of rats, Amicia and Hugo will come to know and trust each other. As they struggle to survive against overwhelming odds, they will fight to find purpose in this brutal, unforgiving world.",
      ProductTitle: "A Plague Tale: Innocence - Windows 10",
      ShortTitle: "A Plague Tale: Innocence",
      SortTitle: "A Plague Tale: Innocence",
      FriendlyTitle: null,
      ShortDescription:
        "Follow the grim tale of young Amicia and her little brother Hugo, in a heartrending journey through the darkest hours of history. Hunted by Inquisition soldiers and surrounded by unstoppable swarms of rats, Amicia and Hugo will come to know and trust each other. As they struggle to survive against overwhelming odds, they will fight to find purpose in this brutal, unforgiving world.",
      SearchTitles: [
        {
          SearchTitleString: "Plague Tale",
          SearchTitleType: "SearchHint",
        },
        {
          SearchTitleString: "Plague",
          SearchTitleType: "SearchHint",
        },
        {
          SearchTitleString: "Rats",
          SearchTitleType: "SearchHint",
        },
        {
          SearchTitleString: "Middle Age",
          SearchTitleType: "SearchHint",
        },
        {
          SearchTitleString: "narrative",
          SearchTitleType: "SearchHint",
        },
        {
          SearchTitleString: "rpg",
          SearchTitleType: "SearchHint",
        },
        {
          SearchTitleString: "tale",
          SearchTitleType: "SearchHint",
        },
      ],
      VoiceTitle: "A Plague Tale: Innocence",
      RenderGroupDetails: null,
      ProductDisplayRanks: [],
      InteractiveModelConfig: null,
      Interactive3DEnabled: false,
      Language: "en",
      Markets: [
        "US",
        "DZ",
        "AR",
        "AU",
        "AT",
        "BH",
        "BD",
        "BE",
        "BR",
        "BG",
        "CA",
        "CL",
        "CN",
        "CO",
        "CR",
        "HR",
        "CY",
        "CZ",
        "DK",
        "EG",
        "EE",
        "FI",
        "FR",
        "DE",
        "GR",
        "GT",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IQ",
        "IE",
        "IL",
        "IT",
        "JP",
        "JO",
        "KZ",
        "KE",
        "KW",
        "LV",
        "LB",
        "LI",
        "LT",
        "LU",
        "MY",
        "MT",
        "MR",
        "MX",
        "MA",
        "NL",
        "NZ",
        "NG",
        "NO",
        "OM",
        "PK",
        "PE",
        "PH",
        "PL",
        "PT",
        "QA",
        "RO",
        "RU",
        "SA",
        "RS",
        "SG",
        "SK",
        "SI",
        "ZA",
        "KR",
        "ES",
        "SE",
        "CH",
        "TW",
        "TH",
        "TT",
        "TN",
        "TR",
        "UA",
        "AE",
        "GB",
        "VN",
        "YE",
        "LY",
        "LK",
        "UY",
        "VE",
        "AF",
        "AX",
        "AL",
        "AS",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AM",
        "AW",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "IO",
        "BN",
        "BF",
        "BI",
        "KH",
        "CM",
        "CV",
        "KY",
        "CF",
        "TD",
        "TL",
        "DJ",
        "DM",
        "DO",
        "EC",
        "SV",
        "GQ",
        "ER",
        "ET",
        "FK",
        "FO",
        "FJ",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "GH",
        "GI",
        "GL",
        "GD",
        "GP",
        "GU",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "HN",
        "AZ",
        "BS",
        "BB",
        "BY",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "KM",
        "CG",
        "CD",
        "CK",
        "CX",
        "CC",
        "CI",
        "CW",
        "JM",
        "SJ",
        "JE",
        "KI",
        "KG",
        "LA",
        "LS",
        "LR",
        "MO",
        "MK",
        "MG",
        "MW",
        "IM",
        "MH",
        "MQ",
        "MU",
        "YT",
        "FM",
        "MD",
        "MN",
        "MS",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "MV",
        "ML",
        "NC",
        "NI",
        "NE",
        "NU",
        "NF",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "RE",
        "RW",
        "BL",
        "MF",
        "WS",
        "ST",
        "SN",
        "MP",
        "PN",
        "SX",
        "SB",
        "SO",
        "SC",
        "SL",
        "GS",
        "SH",
        "KN",
        "LC",
        "PM",
        "VC",
        "TJ",
        "TZ",
        "TG",
        "TK",
        "TO",
        "TM",
        "TC",
        "TV",
        "UM",
        "UG",
        "VI",
        "VG",
        "WF",
        "EH",
        "ZM",
        "ZW",
        "UZ",
        "VU",
        "SR",
        "SZ",
        "AD",
        "MC",
        "SM",
        "ME",
        "VA",
        "NEUTRAL",
      ],
    },
  ],
  MarketProperties: [
    {
      OriginalReleaseDate: "2020-01-23T00:00:00.0000000Z",
      MinimumUserAge: 18,
      ContentRatings: [
        {
          RatingSystem: "COB-AU",
          RatingId: "COB-AU:MA",
          RatingDescriptors: ["COB-AU:Vio", "COB-AU:StrThe"],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "CSRR",
          RatingId: "CSRR:R",
          RatingDescriptors: [],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "DJCTQ",
          RatingId: "DJCTQ:18",
          RatingDescriptors: ["DJCTQ:ExtVio", "DJCTQ:InaLan"],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "ESRB",
          RatingId: "ESRB:M",
          RatingDescriptors: ["ESRB:BloGor", "ESRB:StrLan", "ESRB:Vio"],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "GRB",
          RatingId: "GRB:18",
          RatingDescriptors: ["GRB:Lan", "GRB:FeaHorThr", "GRB:Vio"],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "OFLC-NZ",
          RatingId: "OFLC-NZ:R16",
          RatingDescriptors: [
            "OFLC-NZ:ConDis",
            "OFLC-NZ:OffLan",
            "OFLC-NZ:Vio",
          ],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "PCBP",
          RatingId: "PCBP:18",
          RatingDescriptors: [],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "PEGI",
          RatingId: "PEGI:18",
          RatingDescriptors: ["PEGI:BadLan", "PEGI:Vio"],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "USK",
          RatingId: "USK:16",
          RatingDescriptors: [],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "IARC",
          RatingId: "IARC:18",
          RatingDescriptors: ["IARC:ExtVio", "IARC:StrLan"],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "CCC",
          RatingId: "CCC:18",
          RatingDescriptors: [],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
        {
          RatingSystem: "Microsoft",
          RatingId: "Microsoft:18",
          RatingDescriptors: [],
          RatingDisclaimers: [],
          InteractiveElements: [],
        },
      ],
      RelatedProducts: [],
      UsageData: [
        {
          AggregateTimeSpan: "7Days",
          AverageRating: 4.8,
          PlayCount: 0,
          RatingCount: 41,
          RentalCount: "0",
          TrialCount: "0",
          PurchaseCount: "0",
        },
        {
          AggregateTimeSpan: "30Days",
          AverageRating: 4.6,
          PlayCount: 0,
          RatingCount: 140,
          RentalCount: "0",
          TrialCount: "0",
          PurchaseCount: "0",
        },
        {
          AggregateTimeSpan: "AllTime",
          AverageRating: 4.6,
          PlayCount: 0,
          RatingCount: 7403,
          RentalCount: "0",
          TrialCount: "0",
          PurchaseCount: "0",
        },
      ],
      BundleConfig: null,
      Markets: ["US"],
    },
  ],
  ProductASchema: "Product;3",
  ProductBSchema: "ProductGame;1",
  ProductId: "9ND0CG3LM22K",
  Properties: {
    Attributes: [
      {
        Name: "BroadcastSupport",
        Minimum: null,
        Maximum: null,
        ApplicablePlatforms: null,
        Group: null,
      },
      {
        Name: "SinglePlayer",
        Minimum: null,
        Maximum: null,
        ApplicablePlatforms: ["Desktop"],
        Group: null,
      },
      {
        Name: "XblAchievements",
        Minimum: null,
        Maximum: null,
        ApplicablePlatforms: null,
        Group: null,
      },
      {
        Name: "XblPresence",
        Minimum: null,
        Maximum: null,
        ApplicablePlatforms: null,
        Group: null,
      },
      {
        Name: "XblClubs",
        Minimum: null,
        Maximum: null,
        ApplicablePlatforms: null,
        Group: null,
      },
      {
        Name: "XboxLive",
        Minimum: null,
        Maximum: null,
        ApplicablePlatforms: null,
        Group: null,
      },
    ],
    CanInstallToSDCard: true,
    Category: "Action & adventure",
    Categories: ["Action & adventure", "Role playing"],
    Subcategory: null,
    IsAccessible: false,
    IsDemo: false,
    IsLineOfBusinessApp: false,
    IsPublishedToLegacyWindowsPhoneStore: false,
    IsPublishedToLegacyWindowsStore: false,
    PackageFamilyName:
      "FocusHomeInteractiveSA.APlagueTaleInnocence-Window_4hny5m903y3g0",
    PackageIdentityName: "FocusHomeInteractiveSA.APlagueTaleInnocence-Window",
    PublisherCertificateName: "CN=244B08DA-6A27-4DCD-99EF-F6DCBE2A0C28",
    PublisherId: "24134790",
    SkuDisplayGroups: [
      {
        Id: "01",
        Treatment: "MergeAvailabilities",
      },
    ],
    XboxLiveTier: "Full",
    XboxXPA: null,
    XboxCrossGenSetId: null,
    XboxConsoleGenOptimized: null,
    XboxConsoleGenCompatible: null,
    XboxLiveGoldRequired: false,
    ExtendedMetadata: "9ND0CG3LM22K_4c100a6e-a7da-47a9-9c3c-686a78f18e78",
    XBOX: null,
    OwnershipType: null,
    PdpBackgroundColor: "#FFFFFF",
    HasAddOns: true,
    RevisionId: "2021-12-07T00:59:43.9135471Z",
    ProductGroupId: "c13f9fa5-6f74-4b57-b900-6e215681d233",
    ProductGroupName: "A Plague Tale: Innocence",
  },
  AlternateIds: [
    {
      IdType: "LegacyWindowsStoreProductId",
      Value: "ac449e55-764a-4a2d-95e8-2e92cad5cac3",
    },
    {
      IdType: "LegacyWindowsPhoneProductId",
      Value: "54f3b243-38e6-4be2-9f6c-36d67152430d",
    },
    {
      IdType: "XboxTitleId",
      Value: "1686368600",
    },
    {
      IdType: "LegacyXboxProductId",
      Value: "30444e39-4743-3033-c04c-4d32324b0000",
    },
  ],
  DomainDataVersion: null,
  IngestionSource: "DCE",
  IsMicrosoftProduct: false,
  PreferredSkuId: "0010",
  ProductType: "Game",
  ValidationData: {
    PassedValidation: false,
    RevisionId:
      "2021-12-07T00:59:43.9135471Z||.||367924bb-ee65-4817-9dcb-9a5b3373183e||1152921505693954987||RETAIL||fullrelease",
    ValidationResultUri: "",
  },
  MerchandizingTags: [],
  PartD: "",
  SandboxId: "RETAIL",
  ProductFamily: "Games",
  SchemaVersion: "3",
  IsSandboxedProduct: true,
  ProductKind: "Game",
  ProductPolicies: {},
  DisplaySkuAvailabilities: [
    {
      Sku: {
        LastModifiedDate: "2021-12-07T00:56:40.5776737Z",
        LocalizedProperties: [
          {
            Contributors: [],
            Features: [],
            MinimumNotes: "",
            RecommendedNotes: "",
            ReleaseNotes: "",
            DisplayPlatformProperties: null,
            SkuDescription:
              "Follow the grim tale of young Amicia and her little brother Hugo, in a heartrending journey through the darkest hours of history. Hunted by Inquisition soldiers and surrounded by unstoppable swarms of rats, Amicia and Hugo will come to know and trust each other. As they struggle to survive against overwhelming odds, they will fight to find purpose in this brutal, unforgiving world.",
            SkuTitle: "A Plague Tale: Innocence - Windows 10",
            SkuButtonTitle: "",
            DeliveryDateOverlay: null,
            SkuDisplayRank: [],
            TextResources: null,
            Images: [],
            LegalText: {
              AdditionalLicenseTerms: "",
              Copyright:
                "© 2019 Asobo Studio and Focus Home Interactive. A Plague Tale: Innocence is developed by Asobo Studio and published by Focus Home Interactive.",
              CopyrightUri: "",
              PrivacyPolicy: "",
              PrivacyPolicyUri: "https://www.focus-home.com/privacy-policy/",
              Tou: "",
              TouUri: "",
            },
            Language: "en",
            Markets: [
              "US",
              "DZ",
              "AR",
              "AU",
              "AT",
              "BH",
              "BD",
              "BE",
              "BR",
              "BG",
              "CA",
              "CL",
              "CN",
              "CO",
              "CR",
              "HR",
              "CY",
              "CZ",
              "DK",
              "EG",
              "EE",
              "FI",
              "FR",
              "DE",
              "GR",
              "GT",
              "HK",
              "HU",
              "IS",
              "IN",
              "ID",
              "IQ",
              "IE",
              "IL",
              "IT",
              "JP",
              "JO",
              "KZ",
              "KE",
              "KW",
              "LV",
              "LB",
              "LI",
              "LT",
              "LU",
              "MY",
              "MT",
              "MR",
              "MX",
              "MA",
              "NL",
              "NZ",
              "NG",
              "NO",
              "OM",
              "PK",
              "PE",
              "PH",
              "PL",
              "PT",
              "QA",
              "RO",
              "RU",
              "SA",
              "RS",
              "SG",
              "SK",
              "SI",
              "ZA",
              "KR",
              "ES",
              "SE",
              "CH",
              "TW",
              "TH",
              "TT",
              "TN",
              "TR",
              "UA",
              "AE",
              "GB",
              "VN",
              "YE",
              "LY",
              "LK",
              "UY",
              "VE",
              "AF",
              "AX",
              "AL",
              "AS",
              "AO",
              "AI",
              "AQ",
              "AG",
              "AM",
              "AW",
              "BO",
              "BQ",
              "BA",
              "BW",
              "BV",
              "IO",
              "BN",
              "BF",
              "BI",
              "KH",
              "CM",
              "CV",
              "KY",
              "CF",
              "TD",
              "TL",
              "DJ",
              "DM",
              "DO",
              "EC",
              "SV",
              "GQ",
              "ER",
              "ET",
              "FK",
              "FO",
              "FJ",
              "GF",
              "PF",
              "TF",
              "GA",
              "GM",
              "GE",
              "GH",
              "GI",
              "GL",
              "GD",
              "GP",
              "GU",
              "GG",
              "GN",
              "GW",
              "GY",
              "HT",
              "HM",
              "HN",
              "AZ",
              "BS",
              "BB",
              "BY",
              "BZ",
              "BJ",
              "BM",
              "BT",
              "KM",
              "CG",
              "CD",
              "CK",
              "CX",
              "CC",
              "CI",
              "CW",
              "JM",
              "SJ",
              "JE",
              "KI",
              "KG",
              "LA",
              "LS",
              "LR",
              "MO",
              "MK",
              "MG",
              "MW",
              "IM",
              "MH",
              "MQ",
              "MU",
              "YT",
              "FM",
              "MD",
              "MN",
              "MS",
              "MZ",
              "MM",
              "NA",
              "NR",
              "NP",
              "MV",
              "ML",
              "NC",
              "NI",
              "NE",
              "NU",
              "NF",
              "PW",
              "PS",
              "PA",
              "PG",
              "PY",
              "RE",
              "RW",
              "BL",
              "MF",
              "WS",
              "ST",
              "SN",
              "MP",
              "PN",
              "SX",
              "SB",
              "SO",
              "SC",
              "SL",
              "GS",
              "SH",
              "KN",
              "LC",
              "PM",
              "VC",
              "TJ",
              "TZ",
              "TG",
              "TK",
              "TO",
              "TM",
              "TC",
              "TV",
              "UM",
              "UG",
              "VI",
              "VG",
              "WF",
              "EH",
              "ZM",
              "ZW",
              "UZ",
              "VU",
              "SR",
              "SZ",
              "AD",
              "MC",
              "SM",
              "ME",
              "VA",
              "NEUTRAL",
            ],
          },
        ],
        MarketProperties: [
          {
            FirstAvailableDate: "2020-01-23T00:00:00.0000000Z",
            SupportedLanguages: [
              "en",
              "es",
              "ja",
              "ar",
              "da",
              "nl",
              "pt",
              "it",
              "pt-br",
              "sv",
              "no",
              "ko",
              "fr",
              "pl",
              "ru",
              "de",
              "zh",
              "tr",
              "fi",
              "es-es",
            ],
            PackageIds: null,
            PIFilter: null,
            Markets: ["US"],
          },
        ],
        ProductId: "9ND0CG3LM22K",
        Properties: {
          EarlyAdopterEnrollmentUrl: null,
          FulfillmentData: {
            ProductId: "9ND0CG3LM22K",
            WuBundleId: "897d0a44-0943-4fe0-89cc-7139dd5ee3c3",
            WuCategoryId: "8634d7cc-3901-4c01-9e3b-8896dea1a429",
            PackageFamilyName:
              "FocusHomeInteractiveSA.APlagueTaleInnocence-Window_4hny5m903y3g0",
            SkuId: "0010",
            Content: null,
            PackageFeatures: null,
          },
          FulfillmentType: "MSIXVC",
          FulfillmentPluginId: "Microsoft.GamingServices_8wekyb3d8bbwe",
          HasThirdPartyIAPs: false,
          LastUpdateDate: "2021-12-07T00:56:40.0000000Z",
          HardwareProperties: {
            MinimumHardware: ["kbd", "mse", "xgp", "m08", "v02"],
            RecommendedHardware: ["kbd", "mse", "xgp", "m16", "v04"],
            MinimumProcessor:
              "Intel Core i3-2120 (3.3 GHz)/AMD FX-4100 X4 (3.6 GHz)",
            RecommendedProcessor:
              "Intel Core i5-4690 (3.5 GHz)/AMD FX-8300 (3.3 GHz)",
            MinimumGraphics: "GeForce GTX 660/Radeon HD 7870",
            RecommendedGraphics: "GeForce GTX 970/Radeon RX 480",
          },
          HardwareRequirements: [],
          HardwareWarningList: ["kbd", "mse", "xgp"],
          InstallationTerms: "InstallationTermsRestrictivePC",
          Packages: [
            {
              Applications: [
                {
                  ApplicationId: "Game",
                  DeclarationOrder: 0,
                  Extensions: ["protocol-ms-xbl-6483f158"],
                },
              ],
              Architectures: ["x64"],
              Capabilities: [
                "internetClient",
                "runFullTrust",
                "unvirtualizedResources",
                "Microsoft.requiresNonSMode_8wekyb3d8bbwe",
                "Microsoft.storeFilter.core.notSupported_8wekyb3d8bbwe",
              ],
              DeviceCapabilities: [],
              ExperienceIds: [],
              FrameworkDependencies: [
                {
                  MaxTested: 0,
                  MinVersion: 2533399406837760,
                  PackageIdentity: "Microsoft.DirectXRuntime",
                },
                {
                  MaxTested: 0,
                  MinVersion: 3940651496505344,
                  PackageIdentity: "Microsoft.VCLibs.140.00.UWPDesktop",
                },
              ],
              HardwareDependencies: [],
              HardwareRequirements: [],
              Hash: "",
              HashAlgorithm: "",
              IsStreamingApp: false,
              Languages: [
                "en-us",
                "en-gb",
                "fr-fr",
                "de-de",
                "it-it",
                "es-es",
                "es-mx",
                "pl-pl",
                "pt-br",
                "ru-ru",
                "zh-cn",
                "zh-sg",
                "zh-tw",
                "ja-jp",
                "ko-kr",
              ],
              MaxDownloadSizeInBytes: 44884963328,
              MaxInstallSizeInBytes: 0,
              PackageFormat: "MSIXVC",
              PackageFamilyName:
                "FocusHomeInteractiveSA.APlagueTaleInnocence-Window_4hny5m903y3g0",
              MainPackageFamilyNameForDlc: null,
              PackageFullName: "",
              PackageId: "86801a49-4914-4b18-9481-038f6390a060",
              ContentId: "8b8a960c-e73c-4346-a514-2f0af5991b99",
              KeyId: null,
              PackageRank: 60002,
              PackageUri: "https://productingestionbin1.blob.core.windows.net",
              PlatformDependencies: [
                {
                  MaxTested: 2814750970478592,
                  MinVersion: 2814750970478592,
                  PlatformName: "Windows.Desktop",
                },
              ],
              PlatformDependencyXmlBlob: null,
              ResourceId: "",
              Version: "0",
              PackageDownloadUris: [
                {
                  Rank: 0,
                  Uri: "https://productingestionbin1.blob.core.windows.net",
                },
                {
                  Rank: 1,
                  Uri: "https://productingestionbin1.blob.core.windows.net",
                },
              ],
              DriverDependencies: [],
              FulfillmentData: {
                ProductId: "9ND0CG3LM22K",
                WuBundleId: "897d0a44-0943-4fe0-89cc-7139dd5ee3c3",
                WuCategoryId: "8634d7cc-3901-4c01-9e3b-8896dea1a429",
                PackageFamilyName:
                  "FocusHomeInteractiveSA.APlagueTaleInnocence-Window_4hny5m903y3g0",
                SkuId: "0010",
                PackageContentId: "8b8a960c-e73c-4346-a514-2f0af5991b99",
                Content: null,
                PackageFeatures: null,
              },
            },
          ],
          VersionString: "",
          SkuDisplayGroupIds: ["01"],
          XboxXPA: false,
          BundledSkus: [],
          IsRepurchasable: false,
          SkuDisplayRank: 0,
          DisplayPhysicalStoreInventory: null,
          VisibleToB2BServiceIds: [],
          AdditionalIdentifiers: [],
          IsTrial: false,
          IsPreOrder: false,
          IsBundle: false,
        },
        SkuASchema: "Sku;3",
        SkuBSchema: "SkuGame;1",
        SkuId: "0010",
        SkuType: "full",
        RecurrencePolicy: null,
        SubscriptionPolicyId: null,
      },
      Availabilities: [
        {
          Actions: [
            "Details",
            "Fulfill",
            "Purchase",
            "Browse",
            "Curate",
            "Redeem",
          ],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9V3Q37M0XNNK",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "2022-02-01T09:59:59.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "2021-12-13T10:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            PIFilter: {
              ExclusionProperties: [],
              InclusionProperties: [],
            },
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 44.99,
              MSRP: 44.99,
              TaxType: "TaxesNotIncluded",
              WholesaleCurrencyCode: "USD",
              WholesalePrice: 31.49,
            },
          },
          Properties: {
            OriginalReleaseDate: "2020-01-23T00:00:00.0000000Z",
          },
          SkuId: "0010",
          DisplayRank: 0,
          AlternateIds: [
            {
              IdType: "LegacyTokenIdentifier",
              Value: "30444e39-4743-3033-c04c-4d32324b0000",
            },
          ],
          RemediationRequired: false,
        },
        {
          Actions: ["Details", "Purchase", "Curate"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9X1FXQ1WPQ74",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "2022-02-01T09:59:59.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "2021-12-13T10:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            PIFilter: {
              ExclusionProperties: [],
              InclusionProperties: [],
            },
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "TaxesNotIncluded",
              WholesaleCurrencyCode: "USD",
              WholesalePrice: 0,
            },
          },
          Properties: {
            OriginalReleaseDate: "2020-01-23T00:00:00.0000000Z",
          },
          SkuId: "0010",
          DisplayRank: 1,
          RemediationRequired: true,
          Remediations: [
            {
              RemediationId: "9SQ1C79LQTJJ",
              Type: "Upsell",
              BigId: "CFQ7TTC0KGQ8",
            },
          ],
        },
        {
          Actions: ["Details", "Fulfill", "Browse", "Curate", "Gift"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9WDCC5VK24T3",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "2022-02-01T09:59:59.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "2021-12-13T10:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            PIFilter: {
              ExclusionProperties: [],
              InclusionProperties: [],
            },
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 44.99,
              MSRP: 44.99,
              TaxType: "TaxesNotIncluded",
              WholesaleCurrencyCode: "USD",
              WholesalePrice: 31.49,
            },
            OrderManagementPolicyIdOverride: "microsoft.mint.token",
            GeofencingPolicyId: "GIFTGEO:US",
          },
          Properties: {
            OriginalReleaseDate: "2020-01-23T00:00:00.0000000Z",
          },
          SkuId: "0010",
          DisplayRank: 2,
          AlternateIds: [],
          RemediationRequired: false,
        },
        {
          Actions: ["License", "Browse", "Details"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "B3ZVN9K5J8NF",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "2022-02-01T09:59:59.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "2021-12-13T10:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          LicensingData: {
            SatisfyingEntitlementKeys: [
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0010"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:54f3b243-38e6-4be2-9f6c-36d67152430d:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:ac449e55-764a-4a2d-95e8-2e92cad5cac3:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0002"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0003"],
                LicensingKeyIds: ["1"],
              },
            ],
          },
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "",
              WholesaleCurrencyCode: "",
            },
          },
          Properties: {},
          SkuId: "0010",
          DisplayRank: 3,
          AlternateIds: [
            {
              IdType: "LegacyTokenIdentifier",
              Value: "30444e39-4743-3033-c04c-4d32324b0000",
            },
          ],
          RemediationRequired: false,
        },
        {
          Actions: ["License", "Browse", "Details"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9V09LQ5BWHHT",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "2022-02-01T09:59:59.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "2021-12-13T10:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          LicensingData: {
            SatisfyingEntitlementKeys: [
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0010"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:54f3b243-38e6-4be2-9f6c-36d67152430d:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:ac449e55-764a-4a2d-95e8-2e92cad5cac3:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0002"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0003"],
                LicensingKeyIds: ["1"],
              },
            ],
          },
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "",
              WholesaleCurrencyCode: "",
            },
          },
          Properties: {},
          SkuId: "0010",
          AffirmationId: "9VP428G6BQ82",
          DisplayRank: 4,
          RemediationRequired: false,
        },
        {
          Actions: ["License", "Browse", "Details"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9R3G3SH61XTL",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "2022-02-01T10:00:00.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "2021-12-13T10:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          LicensingData: {
            SatisfyingEntitlementKeys: [
              {
                EntitlementKeys: ["big:CFQ7TTC0KGQ8:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0010"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:54f3b243-38e6-4be2-9f6c-36d67152430d:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:ac449e55-764a-4a2d-95e8-2e92cad5cac3:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0002"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0003"],
                LicensingKeyIds: ["1"],
              },
            ],
          },
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "",
              WholesaleCurrencyCode: "",
            },
          },
          Properties: {},
          SkuId: "0010",
          AffirmationId: "9VP428G6BQ82",
          DisplayRank: 5,
          RemediationRequired: false,
        },
        {
          Actions: ["License", "Details"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9PCK3XSZR7ZS",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Mobile",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Team",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Xbox",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Holographic",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.8828080",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Core",
                },
              ],
            },
            EndDate: "9998-12-30T00:00:00.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "1753-01-01T00:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          LicensingData: {
            SatisfyingEntitlementKeys: [
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0010"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:54f3b243-38e6-4be2-9f6c-36d67152430d:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: [
                  "wes:App:ac449e55-764a-4a2d-95e8-2e92cad5cac3:Full",
                ],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:9ND0CG3LM22K:0002"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0001"],
                LicensingKeyIds: ["1"],
              },
              {
                EntitlementKeys: ["big:BPR9SHS5DHXH:0003"],
                LicensingKeyIds: ["1"],
              },
            ],
          },
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "",
              WholesaleCurrencyCode: "",
            },
          },
          Properties: {},
          SkuId: "0010",
          DisplayRank: 6,
          RemediationRequired: false,
        },
      ],
    },
    {
      Sku: {
        LastModifiedDate: "2021-12-07T00:56:40.5776737Z",
        LocalizedProperties: [
          {
            Contributors: [],
            Features: [],
            MinimumNotes: "",
            RecommendedNotes: "",
            ReleaseNotes: "",
            DisplayPlatformProperties: null,
            SkuDescription:
              "Follow the grim tale of young Amicia and her little brother Hugo, in a heartrending journey through the darkest hours of history. Hunted by Inquisition soldiers and surrounded by unstoppable swarms of rats, Amicia and Hugo will come to know and trust each other. As they struggle to survive against overwhelming odds, they will fight to find purpose in this brutal, unforgiving world.",
            SkuTitle: "A Plague Tale: Innocence - Windows 10",
            SkuButtonTitle: "",
            DeliveryDateOverlay: null,
            SkuDisplayRank: [],
            TextResources: null,
            Images: [],
            LegalText: {
              AdditionalLicenseTerms: "",
              Copyright:
                "© 2019 Asobo Studio and Focus Home Interactive. A Plague Tale: Innocence is developed by Asobo Studio and published by Focus Home Interactive.",
              CopyrightUri: "",
              PrivacyPolicy: "",
              PrivacyPolicyUri: "https://www.focus-home.com/privacy-policy/",
              Tou: "",
              TouUri: "",
            },
            Language: "en",
            Markets: [
              "US",
              "DZ",
              "AR",
              "AU",
              "AT",
              "BH",
              "BD",
              "BE",
              "BR",
              "BG",
              "CA",
              "CL",
              "CN",
              "CO",
              "CR",
              "HR",
              "CY",
              "CZ",
              "DK",
              "EG",
              "EE",
              "FI",
              "FR",
              "DE",
              "GR",
              "GT",
              "HK",
              "HU",
              "IS",
              "IN",
              "ID",
              "IQ",
              "IE",
              "IL",
              "IT",
              "JP",
              "JO",
              "KZ",
              "KE",
              "KW",
              "LV",
              "LB",
              "LI",
              "LT",
              "LU",
              "MY",
              "MT",
              "MR",
              "MX",
              "MA",
              "NL",
              "NZ",
              "NG",
              "NO",
              "OM",
              "PK",
              "PE",
              "PH",
              "PL",
              "PT",
              "QA",
              "RO",
              "RU",
              "SA",
              "RS",
              "SG",
              "SK",
              "SI",
              "ZA",
              "KR",
              "ES",
              "SE",
              "CH",
              "TW",
              "TH",
              "TT",
              "TN",
              "TR",
              "UA",
              "AE",
              "GB",
              "VN",
              "YE",
              "LY",
              "LK",
              "UY",
              "VE",
              "AF",
              "AX",
              "AL",
              "AS",
              "AO",
              "AI",
              "AQ",
              "AG",
              "AM",
              "AW",
              "BO",
              "BQ",
              "BA",
              "BW",
              "BV",
              "IO",
              "BN",
              "BF",
              "BI",
              "KH",
              "CM",
              "CV",
              "KY",
              "CF",
              "TD",
              "TL",
              "DJ",
              "DM",
              "DO",
              "EC",
              "SV",
              "GQ",
              "ER",
              "ET",
              "FK",
              "FO",
              "FJ",
              "GF",
              "PF",
              "TF",
              "GA",
              "GM",
              "GE",
              "GH",
              "GI",
              "GL",
              "GD",
              "GP",
              "GU",
              "GG",
              "GN",
              "GW",
              "GY",
              "HT",
              "HM",
              "HN",
              "AZ",
              "BS",
              "BB",
              "BY",
              "BZ",
              "BJ",
              "BM",
              "BT",
              "KM",
              "CG",
              "CD",
              "CK",
              "CX",
              "CC",
              "CI",
              "CW",
              "JM",
              "SJ",
              "JE",
              "KI",
              "KG",
              "LA",
              "LS",
              "LR",
              "MO",
              "MK",
              "MG",
              "MW",
              "IM",
              "MH",
              "MQ",
              "MU",
              "YT",
              "FM",
              "MD",
              "MN",
              "MS",
              "MZ",
              "MM",
              "NA",
              "NR",
              "NP",
              "MV",
              "ML",
              "NC",
              "NI",
              "NE",
              "NU",
              "NF",
              "PW",
              "PS",
              "PA",
              "PG",
              "PY",
              "RE",
              "RW",
              "BL",
              "MF",
              "WS",
              "ST",
              "SN",
              "MP",
              "PN",
              "SX",
              "SB",
              "SO",
              "SC",
              "SL",
              "GS",
              "SH",
              "KN",
              "LC",
              "PM",
              "VC",
              "TJ",
              "TZ",
              "TG",
              "TK",
              "TO",
              "TM",
              "TC",
              "TV",
              "UM",
              "UG",
              "VI",
              "VG",
              "WF",
              "EH",
              "ZM",
              "ZW",
              "UZ",
              "VU",
              "SR",
              "SZ",
              "AD",
              "MC",
              "SM",
              "ME",
              "VA",
              "NEUTRAL",
            ],
          },
        ],
        MarketProperties: [
          {
            FirstAvailableDate: "2020-01-23T00:00:00.0000000Z",
            SupportedLanguages: [
              "en",
              "es",
              "ja",
              "ar",
              "da",
              "nl",
              "pt",
              "it",
              "pt-br",
              "sv",
              "no",
              "ko",
              "fr",
              "pl",
              "ru",
              "de",
              "zh",
              "tr",
              "fi",
              "es-es",
            ],
            PackageIds: null,
            PIFilter: null,
            Markets: ["US"],
          },
        ],
        ProductId: "9ND0CG3LM22K",
        Properties: {
          EarlyAdopterEnrollmentUrl: null,
          FulfillmentData: {
            ProductId: "9ND0CG3LM22K",
            WuBundleId: "897d0a44-0943-4fe0-89cc-7139dd5ee3c3",
            WuCategoryId: "8634d7cc-3901-4c01-9e3b-8896dea1a429",
            PackageFamilyName:
              "FocusHomeInteractiveSA.APlagueTaleInnocence-Window_4hny5m903y3g0",
            SkuId: "0011",
            Content: null,
            PackageFeatures: null,
          },
          FulfillmentType: "MSIXVC",
          FulfillmentPluginId: "Microsoft.GamingServices_8wekyb3d8bbwe",
          HasThirdPartyIAPs: false,
          LastUpdateDate: "2021-12-07T00:56:40.0000000Z",
          HardwareProperties: {
            MinimumHardware: ["kbd", "mse", "xgp", "m08", "v02"],
            RecommendedHardware: ["kbd", "mse", "xgp", "m16", "v04"],
            MinimumProcessor:
              "Intel Core i3-2120 (3.3 GHz)/AMD FX-4100 X4 (3.6 GHz)",
            RecommendedProcessor:
              "Intel Core i5-4690 (3.5 GHz)/AMD FX-8300 (3.3 GHz)",
            MinimumGraphics: "GeForce GTX 660/Radeon HD 7870",
            RecommendedGraphics: "GeForce GTX 970/Radeon RX 480",
          },
          HardwareRequirements: [],
          HardwareWarningList: ["kbd", "mse", "xgp"],
          InstallationTerms: "InstallationTermsRestrictivePC",
          Packages: [
            {
              Applications: [
                {
                  ApplicationId: "Game",
                  DeclarationOrder: 0,
                  Extensions: ["protocol-ms-xbl-6483f158"],
                },
              ],
              Architectures: ["x64"],
              Capabilities: [
                "internetClient",
                "runFullTrust",
                "unvirtualizedResources",
                "Microsoft.requiresNonSMode_8wekyb3d8bbwe",
                "Microsoft.storeFilter.core.notSupported_8wekyb3d8bbwe",
              ],
              DeviceCapabilities: [],
              ExperienceIds: [],
              FrameworkDependencies: [
                {
                  MaxTested: 0,
                  MinVersion: 2533399406837760,
                  PackageIdentity: "Microsoft.DirectXRuntime",
                },
                {
                  MaxTested: 0,
                  MinVersion: 3940651496505344,
                  PackageIdentity: "Microsoft.VCLibs.140.00.UWPDesktop",
                },
              ],
              HardwareDependencies: [],
              HardwareRequirements: [],
              Hash: "",
              HashAlgorithm: "",
              IsStreamingApp: false,
              Languages: [
                "en-us",
                "en-gb",
                "fr-fr",
                "de-de",
                "it-it",
                "es-es",
                "es-mx",
                "pl-pl",
                "pt-br",
                "ru-ru",
                "zh-cn",
                "zh-sg",
                "zh-tw",
                "ja-jp",
                "ko-kr",
              ],
              MaxDownloadSizeInBytes: 44884963328,
              MaxInstallSizeInBytes: 0,
              PackageFormat: "MSIXVC",
              PackageFamilyName:
                "FocusHomeInteractiveSA.APlagueTaleInnocence-Window_4hny5m903y3g0",
              MainPackageFamilyNameForDlc: null,
              PackageFullName: "",
              PackageId: "86801a49-4914-4b18-9481-038f6390a060",
              ContentId: "8b8a960c-e73c-4346-a514-2f0af5991b99",
              KeyId: null,
              PackageRank: 60002,
              PackageUri: "https://productingestionbin1.blob.core.windows.net",
              PlatformDependencies: [
                {
                  MaxTested: 2814750970478592,
                  MinVersion: 2814750970478592,
                  PlatformName: "Windows.Desktop",
                },
              ],
              PlatformDependencyXmlBlob: null,
              ResourceId: "",
              Version: "0",
              PackageDownloadUris: [
                {
                  Rank: 0,
                  Uri: "https://productingestionbin1.blob.core.windows.net",
                },
                {
                  Rank: 1,
                  Uri: "https://productingestionbin1.blob.core.windows.net",
                },
              ],
              DriverDependencies: [],
              FulfillmentData: {
                ProductId: "9ND0CG3LM22K",
                WuBundleId: "897d0a44-0943-4fe0-89cc-7139dd5ee3c3",
                WuCategoryId: "8634d7cc-3901-4c01-9e3b-8896dea1a429",
                PackageFamilyName:
                  "FocusHomeInteractiveSA.APlagueTaleInnocence-Window_4hny5m903y3g0",
                SkuId: "0011",
                PackageContentId: "8b8a960c-e73c-4346-a514-2f0af5991b99",
                Content: null,
                PackageFeatures: null,
              },
            },
          ],
          VersionString: "",
          SkuDisplayGroupIds: null,
          XboxXPA: false,
          BundledSkus: [],
          IsRepurchasable: false,
          SkuDisplayRank: 2,
          DisplayPhysicalStoreInventory: null,
          VisibleToB2BServiceIds: [],
          AdditionalIdentifiers: [],
          IsTrial: true,
          IsPreOrder: false,
          IsBundle: false,
        },
        SkuASchema: "Sku;3",
        SkuBSchema: "SkuGame;1",
        SkuId: "0011",
        SkuType: "trial",
        RecurrencePolicy: null,
        SubscriptionPolicyId: null,
      },
      Availabilities: [
        {
          Actions: ["Details", "Fulfill"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9VNFZZRPBWB3",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "9998-12-30T00:00:00.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "1753-01-01T00:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "",
              WholesaleCurrencyCode: "",
            },
          },
          Properties: {},
          SkuId: "0011",
          DisplayRank: 0,
          RemediationRequired: false,
        },
        {
          Actions: ["License", "Details"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "9P2LD5TC0GF4",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Desktop",
                },
              ],
            },
            EndDate: "9998-12-30T00:00:00.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "1753-01-01T00:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "",
              WholesaleCurrencyCode: "",
            },
          },
          Properties: {},
          SkuId: "0011",
          DisplayRank: 1,
          RemediationRequired: false,
        },
        {
          Actions: ["License", "Details"],
          AvailabilityASchema: "Availability;3",
          AvailabilityBSchema: "AvailabilityGame;1",
          AvailabilityId: "B20R0C9V27F2",
          Conditions: {
            ClientConditions: {
              AllowedPlatforms: [
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Mobile",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Team",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Xbox",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Holographic",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.8828080",
                },
                {
                  MaxVersion: 2147483647,
                  MinVersion: 0,
                  PlatformName: "Windows.Core",
                },
              ],
            },
            EndDate: "9998-12-30T00:00:00.0000000Z",
            ResourceSetIds: ["1"],
            StartDate: "1753-01-01T00:00:00.0000000Z",
          },
          LastModifiedDate: "2021-12-07T00:59:22.0579725Z",
          Markets: ["US"],
          OrderManagementData: {
            GrantedEntitlementKeys: [],
            Price: {
              CurrencyCode: "USD",
              IsPIRequired: false,
              ListPrice: 0,
              MSRP: 0,
              TaxType: "",
              WholesaleCurrencyCode: "",
            },
          },
          Properties: {},
          SkuId: "0011",
          DisplayRank: 2,
          RemediationRequired: false,
        },
      ],
    },
  ],
};
